### ISSUE TITLE
Cannot send slides to Slajdomat

### ISSUE THREAD

**Issue by lucageatti** [bojanczyk/slajdomat#5]
I downloaded the compiled version of Slajdomat from https://www.mimuw.edu.pl/~bojan/posts/slajdomat-my-homegrown-slide-software .
After trying to send the slides from Figma to the Slajdomat app, the latter logs this message 

`Error receiving slide function toString() { [native code] }`

and no folder appears in the main body.

I tried to compile Slajdomat from source code, and the same issue happens.

**Comment by bojanczyk** [comment]
Thanks Luca,
Is this your first time using the app, or has this issue started to appear after some time of working correctly?
m

**Comment by lucageatti** [comment]
It's the first time.

**Comment by Michcioperz** [comment]
Just an educated guess, but I think what happens here is there is an error when receiving slide, but instead of printing the error to the log the error's toString function gets printed, because of missing parentheses here https://github.com/bojanczyk/slajdomat/blob/f0c8e5a4a877fb706cd3a9bdd3bff331d5a21eee/src/main/server.ts#L440

**Comment by puppis** [comment]
Let me join the discussion and let me thank mikolaj for this insight.

Luca, if you could add the missing parentheses and recompile you will see
what is the error.
Meanwhile, if you like Mikolaj, I can push a correction to this missing
parenthesis bug
(for the other modifications I was suggesting in the previous email, they
can wait, since I'd like to test them more... I have already fixed a case
where they failed).

**Comment by lucageatti** [comment]
Thanks. I'll try it right now. I have ready a pull request with this and other two fixes.

**Comment by lucageatti** [comment]
Thanks to the tips by @Michcioperz and @puppis , it became clear that the problem was that I had first to choose an output directory, and then transfer the slides. Thank you very much.
